# Generated by Django 2.0.5 on 2018-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chrom', models.CharField(max_length=200)),
                ('strand', models.CharField(max_length=200)),
                ('txstart', models.BigIntegerField()),
                ('txend', models.BigIntegerField()),
                ('cdsstart', models.BigIntegerField()),
                ('cdsend', models.BigIntegerField()),
                ('exoncount', models.IntegerField()),
                ('exonstarts', models.TextField()),
                ('exonends', models.TextField()),
                ('score', models.IntegerField()),
                ('name2', models.CharField(max_length=200)),
                ('cdsstartstat', models.CharField(max_length=200)),
                ('cdsendstat', models.CharField(max_length=200)),
                ('exonframes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chrom', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('rsid', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('alternate', models.CharField(max_length=200)),
                ('consequence', models.CharField(blank=True, max_length=200)),
                ('proteinconsequence', models.CharField(blank=True, max_length=200)),
                ('transcriptconsequence', models.CharField(blank=True, max_length=200)),
                ('filter', models.CharField(max_length=200)),
                ('annotation', models.CharField(max_length=200)),
                ('flags', models.CharField(blank=True, max_length=200)),
                ('allelecount', models.IntegerField()),
                ('allelenumber', models.BigIntegerField()),
                ('numberofhomozygotes', models.IntegerField()),
                ('allelefrequency', models.FloatField()),
                ('allelecountafrican', models.IntegerField()),
                ('allelenumberafrican', models.IntegerField()),
                ('homozygotecountafrican', models.IntegerField()),
                ('allelecounteastasian', models.IntegerField()),
                ('allelenumbereastasian', models.IntegerField()),
                ('homozygotecounteastasian', models.IntegerField()),
                ('allelecounteuropeannonfinnish', models.IntegerField()),
                ('allelenumbereuropeannonfinnish', models.IntegerField()),
                ('homozygotecounteuropeannonfinnish', models.IntegerField()),
                ('allelecountfinnish', models.IntegerField()),
                ('allelenumberfinnish', models.IntegerField()),
                ('homozygotecountfinnish', models.IntegerField()),
                ('allelecountlatino', models.IntegerField()),
                ('allelenumberlatino', models.IntegerField()),
                ('homozygotecountlatino', models.IntegerField()),
                ('allelecountother', models.IntegerField()),
                ('allelenumberother', models.IntegerField()),
                ('homozygotecountother', models.IntegerField()),
                ('allelecountsouthasian', models.IntegerField()),
                ('allelenumbersouthasian', models.IntegerField()),
                ('homozygotecountsouthasian', models.IntegerField()),
            ],
        ),
    ]
