# Generated by Django 2.0.5 on 2018-11-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chrom', models.CharField(max_length=200)),
                ('strand', models.CharField(max_length=200)),
                ('txstart', models.BigIntegerField()),
                ('txend', models.BigIntegerField()),
                ('cdsstart', models.BigIntegerField()),
                ('cdsend', models.BigIntegerField()),
                ('exoncount', models.IntegerField()),
                ('exonstarts', models.TextField()),
                ('exonends', models.TextField()),
                ('score', models.IntegerField()),
                ('name2', models.CharField(max_length=200)),
                ('cdsstartstat', models.CharField(max_length=200)),
                ('cdsendstat', models.CharField(max_length=200)),
                ('exonframes', models.TextField()),
            ],
        ),
    ]
