# Generated by Django 2.0.5 on 2018-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chrom', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('rsid', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('alternate', models.CharField(max_length=200)),
                ('consequence', models.CharField(max_length=200)),
                ('proteinconsequence', models.CharField(max_length=200)),
                ('transcriptconsequence', models.CharField(max_length=200)),
                ('filter', models.CharField(max_length=200)),
                ('annotation', models.CharField(max_length=200)),
                ('flags', models.CharField(max_length=200)),
                ('allelecount', models.IntegerField()),
                ('allelenumber', models.BigIntegerField()),
                ('numberofhomozygotes', models.IntegerField()),
                ('allelefrequency', models.FloatField()),
                ('allelecountafrican', models.IntegerField()),
                ('allelenumberafrican', models.IntegerField()),
                ('homozygotecountafrican', models.IntegerField()),
                ('allelecounteastasian', models.IntegerField()),
                ('allelenumbereastasian', models.IntegerField()),
                ('homozygotecounteastasian', models.IntegerField()),
                ('allelecounteuropean_non_finnish_field', models.IntegerField()),
                ('allelenumbereuropean_non_finnish_field', models.IntegerField()),
                ('homozygotecounteuropean_non_finnish_field', models.IntegerField()),
                ('allelecountfinnish', models.IntegerField()),
                ('allelenumberfinnish', models.IntegerField()),
                ('homozygotecountfinnish', models.IntegerField()),
                ('allelecountlatino', models.IntegerField()),
                ('allelenumberlatino', models.IntegerField()),
                ('homozygotecountlatino', models.IntegerField()),
                ('allelecountother', models.IntegerField()),
                ('allelenumberother', models.IntegerField()),
                ('homozygotecountother', models.IntegerField()),
                ('allelecountsouthasian', models.IntegerField()),
                ('allelenumbersouthasian', models.IntegerField()),
                ('homozygotecountsouthasian', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
