# Generated by Django 2.0.5 on 2018-11-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_auto_20181108_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='allelecounteuropean_non_finnish_field',
            new_name='allelecounteuropeannonfinnish',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='allelenumbereuropean_non_finnish_field',
            new_name='allelenumbereuropeannonfinnish',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='homozygotecounteuropean_non_finnish_field',
            new_name='homozygotecounteuropeannonfinnish',
        ),
    ]
