# Generated by Django 2.0.5 on 2018-11-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_auto_20181108_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='consequence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='variant',
            name='flags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='variant',
            name='proteinconsequence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='variant',
            name='transcriptconsequence',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
